name: simple_task

obs_dim: 3  # 3 joint positions
action_dim: 3  # 3 joint positions
keypoint_dim: 2

dataset:
  _target_: diffusion_policy.dataset.simple_task_lowdim_dataset.SimpleTaskLowdimDataset
  dataset_path: /home/sulab1/Workspace/jerry/diffusion/data/joint_positions_dataset.zarr.zip
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: 15  # Fixed to make total 32 (divisible by 8 for UNet)
  seed: 42
  val_ratio: 0.1

env_runner: null  # No environment for real robot offline training

